/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package advertisements;

import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map.Entry;
import java.util.concurrent.TimeUnit;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Ammar
 */
public class MainFrame extends javax.swing.JFrame {
    
    static GraphicsDevice device = GraphicsEnvironment
        .getLocalGraphicsEnvironment().getScreenDevices()[0];
    
    private final HashMap<Integer, Advertisement> ads;
    private Thread displayingThread;
    
    /**
     * Creates new form MainFrame
     * @throws advertisements.InitializingException
     */
    public MainFrame() throws Exception {
        
        Authentication auth = Helper.getAuthentication();
        ads = new HashMap();
        Advertisement[] adsArray = Helper.getAdvertisements(auth);
        
        for (Advertisement ad : adsArray) {
            ads.put(ad.getId(), ad);
        }
        
        ServerAdapter.Initialize(auth, 
                // advertisement added
                ad -> {
                    ads.put(ad.getId(), ad);
                }, 
                // advertisement removed
                ad -> {
                    ads.remove(ad.getId());
                }, 
                // advertisement updated
                ad -> {
                    ads.put(ad.getId(), ad);
                });
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayingPanel = new javax.swing.JPanel();
        displayer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        displayingPanel.setLayout(new java.awt.BorderLayout());

        displayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayingPanel.add(displayer, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(displayingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(displayingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        displayingPanel.setPreferredSize(new Dimension(getWidth(), getHeight()));
        displayer.setPreferredSize(new Dimension(displayingPanel.getWidth(), displayingPanel.getHeight()));
        displayingThread = new Thread(() -> {
            Iterator<Entry<Integer, Advertisement>> i = ads.entrySet().iterator();
            while(true) {
                try {
                    if (ads.isEmpty()) {
                        TimeUnit.SECONDS.sleep(5);
                    } else {
                        try {
                            if (!i.hasNext()) i = ads.entrySet().iterator();
                            Advertisement ad = i.next().getValue();
                            URL url = new URL(ad.getImageUrl());
                            Image image = ImageIO.read(url);
                            displayer.setIcon(new ImageIcon(image.getScaledInstance(displayer.getWidth(), 
                                    displayer.getHeight(), Image.SCALE_SMOOTH)));
                            TimeUnit.SECONDS.sleep(ad.getDuration());
                        } catch (IOException e) {

                        }
                    }
                } catch(InterruptedException e) {
                    
                }
            }
        });
        displayingThread.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            int status = AuthenticationDialog.RET_CANCEL;
            while (!Helper.isReady()) {
                AuthenticationDialog dialog = new AuthenticationDialog(null, true);
                status = dialog.getReturnStatus();
            } 
            MainFrame frame;
            try {
                frame = new MainFrame();
                frame.dispose();
                frame.setUndecorated(true);
                device.setFullScreenWindow(frame);
                frame.setVisible(true);
            } catch (Exception ex) {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel displayer;
    private javax.swing.JPanel displayingPanel;
    // End of variables declaration//GEN-END:variables
}
